import XCTest
@testable import GongCore

/// Every language in Resources/<lang>.lproj has every key (en.lproj, generated by scripts/l10n.py), keeps the
/// format specifiers, and the game texts fit the pixel font and the game-over card.
final class LocalizationTests: XCTestCase {
    static let languages = ["en", "nl", "de", "fr", "es", "it", "pt-BR", "pt-PT", "da", "sv", "nb", "fi",
                            "pl", "cs", "sk", "hu", "ro", "tr", "id", "ms"]
    static let resources = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent()
        .deletingLastPathComponent().appendingPathComponent("Resources")

    static func table(_ lang: String) throws -> [String: String] {
        let url = resources.appendingPathComponent("\(lang).lproj/Localizable.strings")
        let data = try Data(contentsOf: url)
        return try XCTUnwrap(PropertyListSerialization.propertyList(from: data, format: nil) as? [String: String], lang)
    }

    static func specifiers(_ s: String) -> [String] {
        let re = try! NSRegularExpression(pattern: "%(?:(\\d+)\\$)?([@d])")
        let ns = s as NSString
        var next = 0
        return re.matches(in: s, range: NSRange(location: 0, length: ns.length)).map { m in
            let pos = m.range(at: 1).location == NSNotFound ? { next += 1; return next }() : Int(ns.substring(with: m.range(at: 1)))!
            return "\(pos)\(ns.substring(with: m.range(at: 2)))"
        }.sorted()
    }

    func testEveryLanguageHasEveryKeyWithTheSameSpecifiers() throws {
        let en = try Self.table("en")
        XCTAssertGreaterThan(en.count, 60)
        for lang in Self.languages {
            let t = try Self.table(lang)
            XCTAssertEqual(Set(t.keys), Set(en.keys), "\(lang): keys")
            for (k, v) in t {
                XCTAssertEqual(Self.specifiers(v), Self.specifiers(k), "\(lang): \(k) → \(v)")
                XCTAssertFalse(v.trimmingCharacters(in: .whitespaces).isEmpty, "\(lang): \(k) empty")
            }
        }
    }

    func testGameTextsFitThePixelFontAndTheCard() throws {
        for lang in Self.languages {
            let t = try Self.table(lang)
            func f(_ key: String, _ args: CVarArg...) -> String { String(format: t[key] ?? key, arguments: args) }
            let title = f("GAME OVER"), tagline = f("BETTER LUCK NEXT MEETING")
            let lines = [title, tagline, f("NEW HIGH SCORE! %d", 99999), f("SCORE %1$d   HI %2$d", 99999, 99999),
                         f("SCORE %d", 99999), f("HI %d", 99999)]
            for line in lines {
                XCTAssertTrue(PixelFont.canDraw(line), "\(lang): no pixel glyph in \(line)")
                XCTAssertEqual(line, line.uppercased(), "\(lang): \(line) not upper case")
            }
            for score in lines[2...3] {
                let k = GameRenderer.gameOverLayout(title: title, tagline: tagline, score: score)
                let widest = max(PixelFont.width(of: title, scale: k.titleScale), PixelFont.width(of: tagline, scale: 1),
                                 PixelFont.width(of: score, scale: 1))
                XCTAssertLessThanOrEqual(widest + 8, k.w, "\(lang): card too narrow")
                XCTAssertGreaterThanOrEqual(k.y, 3, "\(lang): card too tall")
                XCTAssertEqual(k.titleScale, 2, "\(lang): GAME OVER too long for 2×: \(title)")
                let hearts = GameRenderer.heartOrigin(index: NinjaGame.maxLives - 1)
                let clearOfHearts = k.x - 1 > hearts.x + 5 || k.y - 1 > hearts.y + 5
                XCTAssertTrue(clearOfHearts, "\(lang): card covers the hearts")
            }
            XCTAssertLessThanOrEqual(PixelFont.width(of: f("SCORE %d", 99999), scale: 1), 77, "\(lang): clock score too wide (13 chars)")
        }
    }
}
