#!/usr/bin/env python3
"""Collects every L("…") key from Sources/, writes Resources/en.lproj/Localizable.strings (English = key)
and reports keys missing from or unknown to the other <lang>.lproj files. Run after adding or changing UI text."""
import glob, json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KEY = re.compile(r'\bL\("((?:[^"\\]|\\.)*)"')

def keys():
    found = []
    for path in sorted(glob.glob(os.path.join(ROOT, "Sources", "**", "*.swift"), recursive=True)):
        for k in KEY.findall(open(path, encoding="utf-8").read()):
            if k not in found:
                found.append(k)
    return found

def parse(path):
    pairs = re.findall(r'^"((?:[^"\\]|\\.)*)"\s*=\s*"((?:[^"\\]|\\.)*)";', open(path, encoding="utf-8").read(), re.M)
    return dict(pairs)

def main():
    ks = keys()
    if "--json" in sys.argv:
        print(json.dumps(ks, ensure_ascii=False, indent=1)); return
    en = os.path.join(ROOT, "Resources", "en.lproj")
    os.makedirs(en, exist_ok=True)
    with open(os.path.join(en, "Localizable.strings"), "w", encoding="utf-8") as f:
        f.write("/* Generated by scripts/l10n.py — English: the key is the text. */\n\n")
        for k in ks:
            f.write(f'"{k}" = "{k}";\n')
    ok = True
    for path in sorted(glob.glob(os.path.join(ROOT, "Resources", "*.lproj", "Localizable.strings"))):
        lang = os.path.basename(os.path.dirname(path))
        have = parse(path)
        missing = [k for k in ks if k not in have]
        extra = [k for k in have if k not in ks]
        if missing or extra:
            ok = False
            print(f"{lang}: {len(missing)} missing, {len(extra)} unknown")
            for k in missing: print(f"  - {k}")
            for k in extra: print(f"  + {k}")
    print(f"{len(ks)} keys" + (", all languages complete" if ok else ""))
    sys.exit(0 if ok else 1)

main()
